apiVersion: batch/v1
kind: Job
metadata:
  name: preprocess-dev-pod
spec:
  backoffLimit: 0
  template:
    spec:
      priorityClassName: research-med
      containers:
        - image: ls6-stud-registry.informatik.uni-wuerzburg.de/studkohlmann-pbim-preprocessor:0.1
          name: preprocess
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "2"
              memory: "16Gi"
            requests:
              cpu: "1"
              memory: "12Gi"
          command: ["bash", "-c", "sleep infinity"]
          volumeMounts:
            - mountPath: /data # directory IN the container
              name: data # matches volume-name from below
            - mountPath: /out
              name: out
            - mountPath: /tmp
              name: tmp
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: data
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: "/scratch/p-bim/"
            secretRef:
              name: ceph-secret
            readOnly: true
        - name: out
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: ""/home/stud/kohlmann/MA"
            secretRef:
              name: ceph-secret
        - name: tmp
          emptyDir: {}