apiVersion: batch/v1
kind: Job
metadata:
  name: lux-assemble-s1-interpolate-1500hz
spec:
  backoffLimit: 0
  template:
    spec:
      priorityClassName: research-med
      containers:
        - image: lsx-harbor.informatik.uni-wuerzburg.de/studkohlmann/pbim-preprocessor:0.1
          name: preprocess
          imagePullPolicy: "Always"
          env:
            - name: BASE_PATH
              value: "/data/lux-rezipped.zip"
            - name: OUTPUT_PATH
              value: /out/S1/assembled/interpolate/1500Hz/assembled.dat
            - name: START_TIME
              value: "2014-01-31T12:00:00"
            - name: END_TIME
              value: "2014-02-04T11:59:59"
            - name: RESOLUTION
              value: "0.0006666666666666666"
            - name: STRATEGY
              value: "interpolate"
            - name: FORMAT
              value: "binary"
            - name: CHANNEL
              value: "all"
          resources:
            limits:
              cpu: "2"
              memory: "24Gi"
            requests:
              cpu: "1"
              memory: "8Gi"
          command: ["bash", "./scripts/assemble_lux_dataset.sh"]
          volumeMounts:
            - mountPath: /data # directory IN the container
              name: data # matches volume-name from below
            - mountPath: /out
              name: out
      imagePullSecrets:
        - name: lsx-harbor
      restartPolicy: "Never"
      volumes:
        - name: data
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: "/scratch/p-bim/LUX/"
            secretRef:
              name: ceph-secret
            readOnly: true
        - name: out
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: "/home/stud/kohlmann/MA/assembled/LUX"
            secretRef:
              name: ceph-secret