apiVersion: batch/v1
kind: Job
metadata:
  name: z24-assemble-week-06-25ms
spec:
  backoffLimit: 0
  template:
    spec:
      priorityClassName: research-med
      containers:
        - image: ls6-stud-registry.informatik.uni-wuerzburg.de/studkohlmann-pbim-preprocessor:0.1
          name: preprocess
          imagePullPolicy: "Always"
          env:
            - name: BASE_PATH
              value: "/data"
            - name: OUTPUT_PATH
              value: "/out/week-06/assembled-week-06-1998-04-01T00:00:00-1998-04-06T23:59:59.dat"
            - name: START_TIME
              value: "1998-04-01T00:00:00"
            - name: END_TIME
              value: "1998-04-06T23:59:59"
            - name: RESOLUTION
              value: "0.025"
            - name: STRATEGY
              value: "mean"
            - name: FORMAT
              value: "binary"
          resources:
            limits:
              cpu: "2"
              memory: "16Gi"
            requests:
              cpu: "1"
              memory: "12Gi"
          command: ["bash", "./scripts/assemble_24_dataset.sh"]
          volumeMounts:
            - mountPath: /data # directory IN the container
              name: data # matches volume-name from below
            - mountPath: /out
              name: out
            - mountPath: /tmp
              name: tmp
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: data
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: "/scratch/p-bim-preprocesed/intermediate"
            secretRef:
              name: ceph-secret
            readOnly: true
        - name: out
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: /home/stud/kohlmann/MA/assembled/Z24/weeks-25ms/
            secretRef:
              name: ceph-secret
        - name: tmp
          emptyDir: {}