apiVersion: batch/v1
kind: Job
metadata:
  name: merge-lux-s4-nosampling-250hz
spec:
  backoffLimit: 0
  template:
    spec:
      priorityClassName: research-med
      containers:
        - image: ls6-stud-registry.informatik.uni-wuerzburg.de/studkohlmann-pbim-preprocessor:0.1
          name: preprocess
          imagePullPolicy: "Always"
          env:
            - name: CONFIG_PATH
              value: "/app/configs/lux/anomalous/S4/merge-nosampling.json"
          resources:
            limits:
              cpu: "2"
              memory: "24Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          command: ["bash", "./scripts/merge.sh"]
          volumeMounts:
            - mountPath: /data # directory IN the container
              name: data # matches volume-name from below
            - mountPath: /tmp
              name: tmp
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: data
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: "/home/stud/kohlmann/MA/assembled/"
            secretRef:
              name: ceph-secret
        - name: tmp
          emptyDir: {}